name: Create Pull Request123

on:
  push:
    branches:
      - dev1

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev1
          title: "Feature: Description of changes"
          base: beta
          body: "This pull request addresses the following..."
